# -*- coding: utf-8 -*-
"""DAY_01_Data_Engineering_GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIV4rAkcdnU7be5c0_KN-F_P2ooSSScb
"""

import pandas as pd


pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)


df = pd.read_csv('/content/student_performance.csv')
display(df)

import pandas as pd
df = pd.read_csv('/content/student_performance.csv')
df.head(5)

col_name = df.columns[4]

print(f"Shape of the 5th column ('{col_name}'): {df.iloc[:, 4].shape}")



row_shape = df.iloc[4].shape
print(f"Shape of the 5th row: {row_shape}")

display(df.iloc[[4]])

print(df.columns.tolist())

column_count = len(df.columns)
print(f"Total number of columns: {column_count}")

display(df.dtypes)

display(df.describe(include='all'))

display(df.isnull().sum())

import numpy as np

for i in range(6):
    row = np.random.randint(0, len(df))
    col = np.random.randint(0, len(df.columns))
    df.iat[row, col] = np.nan

display(df.isnull().sum())

import pandas as pd

deleted_indices = df.sample(n=5).index

deleted_rows = df.loc[deleted_indices]

df = df.drop(index=deleted_indices)

print(f"Deleted index: {deleted_indices.tolist()}")
print("\nDeleted Rows:")
display(deleted_rows)

print(f"\n new rows: {len(df)}")

unique_departments = df['department'].unique()
print("Unique Departments:")
display(unique_departments)

dept_counts = df['department'].value_counts()

print("Number of students per department:")

display(dept_counts)

city_counts = df['city'].value_counts()

print("Number of students per city:")
display(city_counts)

chennai_mumbai_students = df[df['city'].isin(['Chennai','Mumbai'])]
display(chennai_mumbai_students[['student_id', 'name', 'city', 'programming_score']])

low_attendance = df[df['attendance_percentage'] > 50]
display(low_attendance)
low  = df['attendance_percentage'].value_counts()

df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
display(df.head())

df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']
tp = df.loc[df['total_score'].idxmin()]
display(tp)

